param(
  [string]$Stage = "stage-0001-small-case"
)

$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "enter-project-context.ps1")

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss K"
$sourcesPath = Join-Path $env:CODEX_3MEN_ROOT "config\learning-sources.json"
$keywordsPath = Join-Path $env:CODEX_3MEN_ROOT "config\keywords.json"
$sources = Get-Content -LiteralPath $sourcesPath -Raw | ConvertFrom-Json
$keywords = Get-Content -LiteralPath $keywordsPath -Raw | ConvertFrom-Json

$wikiDirs = @(
  "knowledge\llmwiki\tia-openness",
  "knowledge\llmwiki\scl",
  "knowledge\llmwiki\wincc-classic-vbs",
  "knowledge\llmwiki\wincc-unified-js",
  "knowledge\llmwiki\tia-v21-current",
  "knowledge\llmwiki\s7-200-smart",
  "knowledge\llmwiki\cli-control",
  "knowledge\gitnexus\scl",
  "knowledge\gitnexus\wincc-classic-vbs",
  "knowledge\gitnexus\wincc-unified-js",
  "knowledge\gitnexus\s7-200-smart",
  "knowledge\gitnexus\cli-control",
  "reports\notion"
)

foreach ($dir in $wikiDirs) {
  $full = Join-Path $env:CODEX_3MEN_ROOT $dir
  if (-not (Test-Path -LiteralPath $full)) {
    New-Item -ItemType Directory -Path $full | Out-Null
  }
}

$tiaNote = @"
# TIA Portal Openness V21 Baseline

Updated: $timestamp
Keyword: `TIA_OPN_V21`

## Source

Official Siemens documentation: $($sources.sources[0].url)

## Digest

The current learning baseline is TIA Portal Openness V21, publication date 03/2026. The first automation target is source export/import for SCL blocks and repeatable CLI bridge control. Any community technique must be checked against this official baseline before being promoted to reusable code.

## Application Rule

Use Openness as the bridge for engineering automation. Keep every export/import operation traceable to a project-local keyword and a generated evidence file.
"@
Set-Content -LiteralPath (Join-Path $env:CODEX_3MEN_ROOT "knowledge\llmwiki\tia-openness\v21-baseline.md") -Value $tiaNote -Encoding UTF8

$sclNote = @"
# SCL Industrial Rules Baseline

Updated: $timestamp
Keywords: `SCL_CASE_OF`, `SCL_OPTIMIZED_ACCESS`

## Digest

SCL examples generated by this project must use clear block interfaces, avoid absolute DB access in optimized blocks, and prefer `CASE ... OF` state machines for sequenced industrial control. Loop constructs must include bounded execution logic so PLC scan time and watchdog behavior remain predictable.
"@
Set-Content -LiteralPath (Join-Path $env:CODEX_3MEN_ROOT "knowledge\llmwiki\scl\industrial-rules-baseline.md") -Value $sclNote -Encoding UTF8

$vbsNote = @"
# WinCC Classic VBS HMIRuntime Baseline

Updated: $timestamp
Keyword: `WINCC_CLASSIC_VBS_HMIRUNTIME`

## Source

Siemens WinCC scripting manual: $($sources.sources[2].url)

## Digest

Classic WinCC VBS examples must start with explicit error handling, access tags through `HMIRuntime.Tags`, and release external COM/OLE resources before script exit. File, SQL, and OLE examples must include failure checks and runtime trace output.
"@
Set-Content -LiteralPath (Join-Path $env:CODEX_3MEN_ROOT "knowledge\llmwiki\wincc-classic-vbs\hmiruntime-baseline.md") -Value $vbsNote -Encoding UTF8

$jsNote = @"
# WinCC Unified JavaScript TagSet Baseline

Updated: $timestamp
Keyword: `WINCC_UNIFIED_JS_TAGSET`

## Source

Official Siemens `Tags.CreateTagSet()` documentation: $($sources.sources[1].url)

## Digest

WinCC Unified examples should prefer `Tags.CreateTagSet()` for grouped tag read/write work. Use modern JavaScript style with `let` and `const`, explicit `try ... catch`, and `HMIRuntime.Trace()` for diagnostics.
"@
Set-Content -LiteralPath (Join-Path $env:CODEX_3MEN_ROOT "knowledge\llmwiki\wincc-unified-js\tagset-baseline.md") -Value $jsNote -Encoding UTF8

$tiaV21Priority = @"
# TIA V21 New CPU, Syntax, and No-Screenshot Automation Priority

Updated: $timestamp
Keywords: `TIA_V21_NEW_CPU`, `TIA_V21_NEW_SYNTAX`, `TIA_CLI_NO_SCREENSHOT`, `TIA_IO_AUTOMATION`

## Official Source Baseline

- New S7-1200/1500 CPU functions and programming recommendations:
  https://docs.tia.siemens.cloud/r/en-us/v21/programming-recommendations-s7-1200-s7-1500/the-new-s7-1200/1500-cpu-functions-and-programming-recommendations-at-a-glance-s7-1200-s7-1500
- Openness export/import:
  https://docs.tia.siemens.cloud/r/en-us/v21/tia-portal-openness-api-for-automation-of-engineering-workflows/export/import
- Version Control Interface export formats:
  https://docs.tia.siemens.cloud/r/en-us/v21/using-tia-portal-version-control-interface/settings-for-the-version-control-interface/setting-the-export-format/overview-of-export-formats
- Hardware Publication Tool command-line export:
  https://docs.tia.siemens.cloud/r/en-us/v21/hardware-publication-tool/exporting-attributes-via-command-line-commands

## Current Learning Focus

Prioritize new CPU families and firmware-dependent behavior, especially S7-1200 G2, S7-1500, S7-1500R/H, and newer firmware rules. Extract practical syntax and programming differences: universal symbolic addressing, optimized block access, larger/newer data types, OPC UA method instruction versions, and migration traps from older absolute-address patterns.

For TIA automation, prefer structured file/API workflows over screenshots:

- Openness export/import for blocks, UDTs, tag tables, HMI data, project texts, and XML-based engineering data.
- VCI and SIMATIC SD for file-based versioning of blocks and Unified scripts.
- Hardware Publication Tool command-line export for hardware attributes.
- Generated artifacts should be inspectable files: `.scl`, `.xml`, `.aml`, `.js`, `.yml`, `.log`, `.json`.

## Validation Boundary

Any claim about actual TIA compile result, CPU catalog behavior, import success, or runtime behavior must be marked ``needs-local-validation`` until the local workstation verifies it through TIA Portal / Openness.
"@
Set-Content -LiteralPath (Join-Path $env:CODEX_3MEN_ROOT "knowledge\llmwiki\tia-v21-current\new-cpu-syntax-cli-priority.md") -Value $tiaV21Priority -Encoding UTF8

$smartPriority = @"
# S7-200 SMART V3 versus V2 Deep-Diff Priority

Updated: $timestamp
Keywords: `S7200SMART_V3_V2_DIFF`, `S7200SMART_FB_USAGE`

## Official Source Baseline

S7-200 SMART V3 System Manual:
https://support.industry.siemens.com/cs/attachments/109978364/S7-200_SMART_V3_system_manual_en-HS.pdf

## Current Learning Focus

Build a V3/V2 migration matrix. Prioritize FB block behavior, FB instance data, static local data, parameter passing, subroutine versus function block use, and syntax or instruction changes that can break migrated V2 projects.

The learning loop must extract:

- How V3 defines and calls FBs.
- How an FB instance stores block parameters and static local data.
- Whether V2 projects require structural edits before V3 import or compile.
- Which syntax differences affect reusable industrial blocks.
- Which behaviors must be verified in STEP 7-Micro/WIN SMART locally.

## Validation Boundary

Any V3/V2 compile, import, download, or online behavior must be marked ``needs-local-validation`` until checked on the local Windows workstation.
"@
Set-Content -LiteralPath (Join-Path $env:CODEX_3MEN_ROOT "knowledge\llmwiki\s7-200-smart\v3-v2-fb-diff-priority.md") -Value $smartPriority -Encoding UTF8

$sclCode = @'
FUNCTION_BLOCK "FB_MotorControl_CaseOf"
{ S7_Optimized_Access := 'TRUE' }
VERSION : 0.1
   VAR_INPUT
      StartCmd : Bool;
      StopCmd : Bool;
      FaultReset : Bool;
      FeedbackRunning : Bool;
   END_VAR
   VAR_OUTPUT
      MotorRun : Bool;
      Fault : Bool;
      State : Int;
   END_VAR
   VAR
      Step : Int := 0;
   END_VAR

BEGIN
   // Keywords: SCL_CASE_OF, SCL_OPTIMIZED_ACCESS
   CASE #Step OF
      0:
         #MotorRun := FALSE;
         #Fault := FALSE;
         #State := 0;
         IF #StartCmd THEN
            #Step := 10;
         END_IF;
      10:
         #MotorRun := TRUE;
         #State := 10;
         IF #StopCmd THEN
            #Step := 0;
         ELSIF NOT #FeedbackRunning THEN
            #Step := 900;
         END_IF;
      900:
         #MotorRun := FALSE;
         #Fault := TRUE;
         #State := 900;
         IF #FaultReset THEN
            #Step := 0;
         END_IF;
      ELSE
         #MotorRun := FALSE;
         #Fault := TRUE;
         #State := 999;
         #Step := 900;
   END_CASE;
END_FUNCTION_BLOCK
'@
Set-Content -LiteralPath (Join-Path $env:CODEX_3MEN_ROOT "knowledge\gitnexus\scl\fb_motor_control_case_of.scl") -Value $sclCode -Encoding UTF8

$vbsCode = @'
' Keywords: WINCC_CLASSIC_VBS_HMIRUNTIME
Option Explicit
On Error Resume Next

Dim tag, currentValue
Set tag = HMIRuntime.Tags("Motor_StartCmd")
currentValue = tag.Read

If Err.Number <> 0 Then
    HMIRuntime.Trace "Tag read failed: " & Err.Description
    Err.Clear
Else
    tag.Write CBool(Not currentValue)
    If Err.Number <> 0 Then
        HMIRuntime.Trace "Tag write failed: " & Err.Description
        Err.Clear
    Else
        HMIRuntime.Trace "Motor_StartCmd toggled safely."
    End If
End If

Set tag = Nothing
'@
Set-Content -LiteralPath (Join-Path $env:CODEX_3MEN_ROOT "knowledge\gitnexus\wincc-classic-vbs\read_write_tag_safe.vbs") -Value $vbsCode -Encoding UTF8

$jsCode = @'
// Keywords: WINCC_UNIFIED_JS_TAGSET
export function ToggleMotorTags() {
  try {
    const tagSet = Tags.CreateTagSet(["Motor_StartCmd", "Motor_StopCmd"]);
    tagSet.Read();

    const startTag = tagSet("Motor_StartCmd");
    const stopTag = tagSet("Motor_StopCmd");

    startTag.Value = !startTag.Value;
    stopTag.Value = false;
    tagSet.Write();

    HMIRuntime.Trace("Motor tag set updated.");
  } catch (err) {
    HMIRuntime.Trace(`ToggleMotorTags failed: ${err.message}`);
  }
}
'@
Set-Content -LiteralPath (Join-Path $env:CODEX_3MEN_ROOT "knowledge\gitnexus\wincc-unified-js\tagset_read_write.js") -Value $jsCode -Encoding UTF8

$tiaCliCode = @'
# Keywords: TIA_CLI_NO_SCREENSHOT, TIA_IO_AUTOMATION
# Purpose: no-screenshot automation skeleton. Local paths must be verified on the engineering workstation.

param(
  [Parameter(Mandatory = $true)]
  [string]$TiaInstallBin,

  [Parameter(Mandatory = $true)]
  [string]$ProjectPath,

  [Parameter(Mandatory = $true)]
  [string]$OutputDir
)

$ErrorActionPreference = "Stop"

$publicationTool = Join-Path $TiaInstallBin "Siemens.Automation.Cax.PublicationTool.Mdd.Console.exe"
if (-not (Test-Path -LiteralPath $publicationTool)) {
  throw "Hardware Publication Tool console executable not found: $publicationTool"
}

if (-not (Test-Path -LiteralPath $OutputDir)) {
  New-Item -ItemType Directory -Path $OutputDir | Out-Null
}

# Exact parameters are version- and installation-dependent.
# Keep this as a local-validation target before production use.
& $publicationTool /help | Tee-Object -FilePath (Join-Path $OutputDir "hardware-publication-tool-help.log")
'@
Set-Content -LiteralPath (Join-Path $env:CODEX_3MEN_ROOT "knowledge\gitnexus\cli-control\tia_no_screenshot_export_skeleton.ps1") -Value $tiaCliCode -Encoding UTF8

$smartFbNote = @'
// Keywords: S7200SMART_V3_V2_DIFF, S7200SMART_FB_USAGE
// Purpose: learning placeholder for S7-200 SMART V3/V2 FB usage.
// This is not a verified importable source file. Treat as needs-local-validation.

// Study targets:
// 1. Compare V3 FB instance data with V2 project structure.
// 2. Record parameter passing rules and static local data behavior.
// 3. Verify compile/import behavior in STEP 7-Micro/WIN SMART.
// 4. Convert confirmed patterns into real code assets only after local validation.
'@
Set-Content -LiteralPath (Join-Path $env:CODEX_3MEN_ROOT "knowledge\gitnexus\s7-200-smart\v3-v2-fb-study-notes.scl") -Value $smartFbNote -Encoding UTF8

$graphPath = Join-Path $env:CODEX_3MEN_ROOT "knowledge\graphify\graph.jsonl"
if (Test-Path -LiteralPath $graphPath) {
  $seenGraphLines = @{}
  $dedupedGraphLines = New-Object System.Collections.Generic.List[string]
  foreach ($line in (Get-Content -LiteralPath $graphPath)) {
    if ([string]::IsNullOrWhiteSpace($line)) {
      continue
    }
    try {
      $item = $line | ConvertFrom-Json
      if ($item.schema) {
        $key = "schema|$($item.schema)"
      } else {
        $key = "$($item.subject)|$($item.predicate)|$($item.object)"
      }
    } catch {
      $key = "raw|$line"
    }
    if (-not $seenGraphLines.ContainsKey($key)) {
      $seenGraphLines[$key] = $true
      $dedupedGraphLines.Add($line) | Out-Null
    }
  }
  Set-Content -LiteralPath $graphPath -Value $dedupedGraphLines -Encoding UTF8
} else {
  '{"schema":"codex-3men.graphify.v1","created":"2026-05-26","note":"Entity-relation triples for project-local automation knowledge."}' | Set-Content -LiteralPath $graphPath -Encoding UTF8
}
$triples = @(
  @{ subject = "TIA Portal Openness V21"; predicate = "exports_imports"; object = "SCL blocks"; keywords = @("TIA_OPN_V21", "CLI_EXPORT_IMPORT"); source = $sources.sources[0].url },
  @{ subject = "SCL CASE OF"; predicate = "implements"; object = "bounded state machine"; keywords = @("SCL_CASE_OF"); source = "knowledge/gitnexus/scl/fb_motor_control_case_of.scl" },
  @{ subject = "WinCC Classic VBS"; predicate = "uses"; object = "HMIRuntime.Tags"; keywords = @("WINCC_CLASSIC_VBS_HMIRUNTIME"); source = $sources.sources[2].url },
  @{ subject = "WinCC Unified JavaScript"; predicate = "uses"; object = "Tags.CreateTagSet"; keywords = @("WINCC_UNIFIED_JS_TAGSET"); source = $sources.sources[1].url },
  @{ subject = "TIA Portal V21"; predicate = "prioritizes_learning"; object = "new CPU functions and SCL syntax"; keywords = @("TIA_V21_NEW_CPU", "TIA_V21_NEW_SYNTAX"); source = "config/learning-priorities.json" },
  @{ subject = "TIA automation"; predicate = "avoids"; object = "screenshot-only workflows"; keywords = @("TIA_CLI_NO_SCREENSHOT"); source = "knowledge/gitnexus/cli-control/tia_no_screenshot_export_skeleton.ps1" },
  @{ subject = "S7-200 SMART V3"; predicate = "requires_deep_diff_against"; object = "S7-200 SMART V2"; keywords = @("S7200SMART_V3_V2_DIFF"); source = "config/learning-priorities.json" },
  @{ subject = "S7-200 SMART FB"; predicate = "needs_local_validation_for"; object = "instance data and syntax differences"; keywords = @("S7200SMART_FB_USAGE"); source = "knowledge/llmwiki/s7-200-smart/v3-v2-fb-diff-priority.md" }
)
foreach ($triple in $triples) {
  $key = "$($triple.subject)|$($triple.predicate)|$($triple.object)"
  $exists = $false
  foreach ($line in (Get-Content -LiteralPath $graphPath)) {
    if ([string]::IsNullOrWhiteSpace($line)) {
      continue
    }
    try {
      $item = $line | ConvertFrom-Json
      $existingKey = "$($item.subject)|$($item.predicate)|$($item.object)"
      if ($existingKey -eq $key) {
        $exists = $true
        break
      }
    } catch {
    }
  }
  if (-not $exists) {
    ($triple | ConvertTo-Json -Compress) | Add-Content -LiteralPath $graphPath -Encoding UTF8
  }
}

$reportTemplate = @'
# Codex-3men Stage 0001 Small Case Report

Report time: {{timestamp}}
Executor: Codex Autonomous Learning Stack

## 1. Important Findings

- TIA Portal Openness V21 is the current official Openness baseline found for this run. It anchors CLI bridge and SCL export/import learning.
- WinCC Unified JavaScript `Tags.CreateTagSet()` is the current official tag-batch baseline found for this run.
- WinCC Classic VBS must remain `HMIRuntime`-driven and defensive around external resources and tag read/write failures.

## 2. Memory Consolidation

- LLM Wiki updated:
  - `knowledge/llmwiki/tia-openness/v21-baseline.md`
  - `knowledge/llmwiki/scl/industrial-rules-baseline.md`
  - `knowledge/llmwiki/wincc-classic-vbs/hmiruntime-baseline.md`
  - `knowledge/llmwiki/wincc-unified-js/tagset-baseline.md`
- GitNexus assets updated:
  - `knowledge/gitnexus/scl/fb_motor_control_case_of.scl`
  - `knowledge/gitnexus/wincc-classic-vbs/read_write_tag_safe.vbs`
  - `knowledge/gitnexus/wincc-unified-js/tagset_read_write.js`
- Graphify updated:
  - `knowledge/graphify/graph.jsonl`

## 3. Code Snapshots

### SCL

`FB_MotorControl_CaseOf` uses `CASE ... OF`, optimized block access, explicit interface variables, and a fault state.

### WinCC Classic VBS

`read_write_tag_safe.vbs` uses `On Error Resume Next`, `HMIRuntime.Tags("Motor_StartCmd")`, read/write checks, and releases the tag object.

### WinCC Unified JavaScript

`tagset_read_write.js` uses `Tags.CreateTagSet(["Motor_StartCmd", "Motor_StopCmd"])`, `try ... catch`, and `HMIRuntime.Trace()`.

## 4. Graphify Relationship Updates

- `TIA Portal Openness V21` --exports_imports--> `SCL blocks`
- `SCL CASE OF` --implements--> `bounded state machine`
- `WinCC Classic VBS` --uses--> `HMIRuntime.Tags`
- `WinCC Unified JavaScript` --uses--> `Tags.CreateTagSet`

## 5. Prompt Revisions

- Always resolve the keyword first from `config/keywords.json`.
- Generate a small executable or inspectable case before scaling to a long-running learning pass.
- Promote community content only after official-source confirmation or reproducible local proof.

## 6. Next Keywords

- `TIA_OPENNESS_COMPILE_LOG`
- `WINCC_VBS_ADO_EXPORT`
- `UNIFIED_JS_DYNAMIC_SCREEN`
- `SCL_WATCHDOG_SAFE_LOOP`
'@

$report = $reportTemplate.Replace("{{timestamp}}", $timestamp)

$reportPath = Join-Path $env:CODEX_3MEN_ROOT "reports\notion\$Stage.md"
Set-Content -LiteralPath $reportPath -Value $report -Encoding UTF8

$summary = [ordered]@{
  stage = $Stage
  timestamp = $timestamp
  wikiFiles = 4
  gitnexusAssets = 3
  graphTriplesAdded = 4
  report = $reportPath
  keywordCount = $keywords.keywords.Count
}

$summary | ConvertTo-Json -Depth 5
